# Generated by Django 3.1.1 on 2020-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsmodel',
            name='uuid',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='uuid',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
