# Generated by Django 3.1.1 on 2020-10-05 20:28

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mod', '0002_auto_20201005_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('access_code', models.CharField(max_length=60)),
                ('selected_course', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('uuid', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['username'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='uuid',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='uuid',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='ProyectOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=60)),
                ('cover_image', models.URLField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.classroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.studentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='mod.StudentModel'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(to='mod.TeacherModel'),
        ),
    ]
