# Generated by Django 3.1.2 on 2020-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Congratulation',
            },
        ),
        migrations.CreateModel(
            name='AdviceModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Motivational taks ok',
            },
        ),
        migrations.CreateModel(
            name='AdviceModel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Motivational overdue task',
            },
        ),
        migrations.DeleteModel(
            name='AdviceModel',
        ),
    ]
